name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[no_ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PACKAGE_USERNAME }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: drawbridge
    needs: build

    env:
      DOCKER_BUILDKIT: 1
      WAIT_TIME: 30
      CONTAINER_NAME: "drawbridge_prod"
      ENV_FILE_PATH: "/opt/ozf-projects/drawbridge/prod.env"

    steps:
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PACKAGE_USERNAME }}
          password: ${{ secrets.PACKAGE_TOKEN }}

      - name: Deploy Docker Container
        run: |
          if [ "$(docker ps -a -q -f name=${CONTAINER_NAME})" ]; then
            docker rm -f ${CONTAINER_NAME}
          fi
          docker pull ghcr.io/ozfortress/drawbridge:main
          docker run -d \
            --name ${CONTAINER_NAME} \
            --network traefik-public \
            --env-file ${{ env.ENV_FILE_PATH }} \
            -v "/opt/ozf-projects/drawbridge/logs/${CONTAINER_NAME}":/app/logs \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.drawbridge-prod.rule=Host(\`drawbridge.ozf.shigbeard.xyz\`)" \
            --label "traefik.http.routers.drawbridge-prod.tls=true" \
            --label "traefik.http.routers.drawbridge-prod.tls.certresolver=le" \
            --label "traefik.http.services.drawbridge-prod.loadbalancer.server.port=3000" \
            --label "traefik.docker.network=traefik-public" \
            ghcr.io/ozfortress/drawbridge:main
